name: Deploy Prerelease

on:
  workflow_run:
    workflows: ["Prerelease"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_STAGING_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_STAGING_HOST_FINGERPRINT }}

      # - name: Adding Known Hosts
      #   run: echo "${{ secrets.SSH_STAGING_HOST_FINGERPRINT }}" >> ~/.ssh/known_hosts

      - name: Deploy using server side script
        run: ssh -T ${{ secrets.SSH_USER }}@${{ secrets.SSH_STAGING_HOST }}
