name: Deploy Prerelease

on:
  workflow_run:
    workflows: [Prerelease]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_STAGING_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_STAGING_HOST_FINGERPRINT }}
          config: |
            Host *
              HostKeyAlgorithms ssh-rsa-cert-v01@openssh.com,ssh-rsa
              StrictHostKeyChecking yes

      - name: Deploy using server side script
        run: ssh -qT ${{ secrets.SSH_USER }}@${{ secrets.SSH_STAGING_HOST }}
